openapi: 3.1.1
info:
  title: OpenAPI 3.1.1 sdk nested classes example
  version: 1
paths:
  /business/providers/domains:
    get:
      tags:
        - business
        - providers
        - domains
      operationId: business.providers.domains.get
      responses:
        '200':
          content:
            '*/*':
              schema:
                type: string
          description: OK
    post:
      tags:
        - providers
        - domains
        - business
      operationId: business.providers.domains.post
      responses:
        '200':
          content:
            '*/*':
              schema:
                type: string
          description: OK
    put:
      tags:
        - domains
      responses:
        '200':
          content:
            '*/*':
              schema:
                type: string
          description: OK
  /locations/businesses:
    get:
      tags:
        - locations
        - business
      operationId: business.get
      responses:
        '200':
          content:
            '*/*':
              schema:
                type: string
          description: OK
  /locations:
    get:
      tags:
        - locations
      operationId: get
      responses:
        '200':
          content:
            '*/*':
              schema:
                type: string
          description: OK
